name: flutter_app
description: Chatbot flutter app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+6

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  multi_select_flutter: ^4.1.3
  dialogflow_flutter: ^1.0.0
  blinking_text: ^1.0.2
  geolocator: 10.0.0
  geocoding: 2.0.5
  url_launcher: 6.1.12
  connectivity: ^3.0.2
  expandable_text: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  rxdart: ^0.27.7
  cupertino_icons: ^1.0.2
  share: ^2.0.0
  flutter_platform_widgets: ^3.3.5
  intl: ^0.18.1
  equatable: ^2.0.0
  flutter_bloc: 8.1.3

  loading_gifs: ^0.3.0
  streaming_shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/credentials.json
    - assets/images/placeholder.jpg
    - assets/images/thumbnail_default.png
    - assets/images/person_placeholder.png
    - assets/images/tmdb_logo.png
    - assets/images/just_watch_logo.png
    - assets/flags/
    - assets/icon/app_icon.png
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700